image: "inetsix/runner-python:2.7"

stages:
  - code_quality
  - deploy
  - cleanup

.cvp_python: &cvp_tasks
  before_script:
    - pip install -r requirements.txt
    - pip install git+https://github.com/titom73/arista-cvp-scripts.git
    - pip install git+https://github.com/aristanetworks/cvprac.git@develop
    - chmod -R 755 .

linting:ansible:
  stage: code_quality
  before_script:
    - pip install -r requirements.txt
    - chmod -R 755 .
  script:
    - echo $PWD 
    - ansible-playbook playbook.build.customers.vlans.yml -i inventory.ini --syntax-check
  only:
    - master

deploy:vlan:
  <<: *cvp_tasks
  stage: deploy
  script:
    - date
    - echo $PWD 
    - ansible-playbook playbook.build.customers.vlans.yml -i inventory.ini
    - cvp-configlet-manager -j configlets/customers.vlans.actions.json
  only:
    variables:
      - $CVP_ROLLBACK == "no"
      - $CVP_ROLLBACK == null
    changes:
      - group_vars/leaf/vlan_customers.yaml
  artifacts:
    name: "CUSTOMERS-VLANS-DEPLOY-$CI_COMMIT_REF_NAME"
    paths:
      - configlets/
      - group_vars/

deploy:rollback:
  <<: *cvp_tasks
  stage: cleanup
  script:
    - export CVP_CC_APPLY=true
    - ansible-playbook playbook.build.customers.vlans.yml -i inventory.ini
    - cvp-configlet-manager -j configlets/rollback.customers.vlans.actions.json
  only:
    variables:
      - $CVP_ROLLBACK == "yes"