- name: Build 
  hosts: all
  connection: local
  gather_facts: no
  tags: cleanup
  run_once: true
  tasks:
    - name: remove host build temp directory
      file: 
        path: "configlets" 
        state: absent 
        mode: 0755
      delegate_to: localhost
    - name: create host build temp directory
      file: 
        path: "configlets" 
        state: directory
        mode: 0755
      delegate_to: localhost


- name: Build Configlets
  hosts: leaf
  connection: local
  gather_facts: no
  tags: generate
  run_once: true
  roles:
    - configlet.customers.vlans